openapi: 3.2.0
info:
  title: QuasarDB Tables API
  version: 3.15.0-nightly.0
  description: Find out more at https://doc.quasardb.net
servers:
- url: /api
security:
- Bearer: []
- UrlParam: []
tags:
- name: Tables
paths:
  /tables/{name}.csv:
    get:
      operationId: get-table-csv
      summary: Fetch the rows of a table between a given date range and return as csv
      parameters:
      - in: path
        name: name
        required: true
        schema:
          type: string
      - in: query
        name: start
        required: true
        schema:
          type: string
      - in: query
        name: end
        required: true
        schema:
          type: string
      responses:
        '400':
          description: Bad Request.
        '500':
          description: Internal Error.
        '200':
          description: Successful operation
          content:
            text/csv:
              schema:
                type: string
                format: binary
      tags:
      - Tables
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
    UrlParam:
      type: apiKey
      name: token
      in: query
