swagger: '2.0'
info:
  title: QuasarDB cluster Prometheus API
  version: 3.15.0-nightly.0
  description: Find out more at https://doc.quasardb.net
basePath: /api
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
security:
- Bearer: []
- UrlParam: []
tags:
- name: Prometheus
paths:
  /prometheus/read:
    post:
      operationId: prometheusRead
      description: The read endpoint for remote Prometheus storage
      parameters:
      - name: query
        in: body
        schema:
          type: string
          format: binary
        required: true
        description: The samples in snappy-encoded protocol buffer format sent from Prometheus
      security: []
      consumes:
      - application/x-protobuf
      produces:
      - application/x-protobuf
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: binary
        '500':
          schema:
            $ref: '#/definitions/QdbError'
          description: Internal Error.
      tags:
      - Prometheus
  /prometheus/write:
    post:
      operationId: prometheusWrite
      description: The write endpoint for remote Prometheus storage
      parameters:
      - name: timeseries
        in: body
        schema:
          type: string
          format: binary
        required: true
        description: The samples in snappy-encoded protocol buffer format sent from Prometheus
      security: []
      consumes:
      - application/x-protobuf
      produces:
      - application/x-protobuf
      responses:
        '200':
          description: OK
        '500':
          schema:
            $ref: '#/definitions/QdbError'
          description: Internal Error.
      tags:
      - Prometheus
definitions:
  QdbError:
    properties:
      message:
        type: string
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
  UrlParam:
    type: apiKey
    name: token
    in: query
