openapi: 3.2.0
info:
  title: QuasarDB Login API
  version: 3.15.0-nightly.0
  description: Find out more at https://doc.quasardb.net
servers:
- url: /api
security:
- Bearer: []
- UrlParam: []
tags:
- name: Login
paths:
  /login:
    post:
      operationId: login
      security: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '401':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QdbError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credential'
        description: The user's credential
        required: true
      tags:
      - Login
      summary: Login
      x-summary-source: derived
components:
  schemas:
    Token:
      type: object
      properties:
        token:
          type: string
    QdbError:
      properties:
        message:
          type: string
    Credential:
      type: object
      properties:
        username:
          type: string
        secret_key:
          type: string
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
    UrlParam:
      type: apiKey
      name: token
      in: query
