swagger: '2.0'
info:
  title: QuasarDB cluster tags API
  version: 3.15.0-nightly.0
  description: Find out more at https://doc.quasardb.net
basePath: /api
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
security:
- Bearer: []
- UrlParam: []
tags:
- name: tags
paths:
  /tags:
    get:
      operationId: get-tags
      parameters:
      - in: query
        name: regex
        type: string
        required: false
      responses:
        '400':
          schema:
            $ref: '#/definitions/QdbError'
          description: Bad Request.
        '500':
          schema:
            $ref: '#/definitions/QdbError'
          description: Internal Error.
        '200':
          schema:
            $ref: '#/definitions/QueryResult'
          description: Successful Operation
          examples:
            application/json:
              tables:
              - name: tags
                columns:
                - name: tag
                  type: string
                  data:
                  - tag1
                  - tag2
      tags:
      - tags
      summary: Query the database for all tag names
definitions:
  QueryTable:
    properties:
      name:
        type: string
      columns:
        type: array
        items:
          $ref: '#/definitions/QueryColumn'
  QueryColumn:
    properties:
      name:
        type: string
      type:
        type: string
      data:
        type: array
        items:
          type: object
  QdbError:
    properties:
      message:
        type: string
  QueryResult:
    type: object
    properties:
      tables:
        type: array
        items:
          $ref: '#/definitions/QueryTable'
    required:
    - tables
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
  UrlParam:
    type: apiKey
    name: token
    in: query
