openapi: 3.2.0
info:
  title: QuasarDB Status API
  version: 3.15.0-nightly.0
  description: Find out more at https://doc.quasardb.net
servers:
- url: /api
security:
- Bearer: []
- UrlParam: []
tags:
- name: Status
paths:
  /status/liveness:
    get:
      security: []
      operationId: status-liveness
      responses:
        '200':
          description: Successful operation
        '500':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QdbError'
      tags:
      - Status
      summary: Status liveness
      x-summary-source: derived
  /status/readiness:
    get:
      security: []
      operationId: status-readiness
      responses:
        '200':
          description: Successful operation
        '500':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QdbError'
      tags:
      - Status
      summary: Status readiness
      x-summary-source: derived
components:
  schemas:
    QdbError:
      properties:
        message:
          type: string
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
    UrlParam:
      type: apiKey
      name: token
      in: query
