openapi: 3.2.0
info:
  title: QuasarDB Cluster API
  version: 3.15.0-nightly.0
  description: Find out more at https://doc.quasardb.net
servers:
- url: /api
security:
- Bearer: []
- UrlParam: []
tags:
- name: Cluster
  description: Operational statistics about the QuasarDB cluster
paths:
  /cluster:
    get:
      operationId: get-cluster
      responses:
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QdbError'
        '500':
          description: Internal Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QdbError'
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster'
              example:
                memoryTotal: 312204568
                memoryUsed: 55440601
                diskTotal: 24408800000
                diskUsed: 801210000
                nodes:
                - 172.14.0.2:2836
                - 172.14.0.3:2836
                status: stable
      tags:
      - Cluster
      summary: Get a summary of the cluster status
  /cluster/nodes/{id}:
    get:
      operationId: get-node
      parameters:
      - name: id
        in: path
        required: true
        description: The node's id (address and host)
        schema:
          type: string
      responses:
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QdbError'
        '500':
          description: Internal Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QdbError'
        '404':
          description: The requested resource could not be found but may be available again in the future.
          content:
            application/json:
              schema:
                type: string
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
              example:
                id: 172.14.0.2:2836
                os: Linux
                quasardbVersion: 1.0.1
                memoryTotal: 22857027000
                memoryUsed: 2515456400
                diskTotal: 99832160000
                diskUsed: 360678000
                cpuTotal: 2
                cpuUsed: 1.84
      tags:
      - Cluster
      summary: Get information about a single node in the cluster
components:
  schemas:
    Node:
      type: object
      properties:
        id:
          type: string
        os:
          type: string
        quasardbVersion:
          type: string
        memoryTotal:
          type: integer
          minimum: 0
        memoryUsed:
          type: integer
          minimum: 0
        diskTotal:
          type: integer
          minimum: 0
        diskUsed:
          type: integer
          minimum: 0
        cpuTotal:
          type: integer
          minimum: 0
        cpuUsed:
          type: integer
          minimum: 0
      required:
      - id
      - os
      - quasardbVersion
      - memoryTotal
      - memoryUsed
      - diskTotal
      - diskUsed
      - cpuTotal
      - cpuUsed
    Cluster:
      type: object
      properties:
        memoryTotal:
          type: integer
          minimum: 0
        memoryUsed:
          type: integer
          minimum: 0
        diskTotal:
          type: integer
          minimum: 0
        diskUsed:
          type: integer
          minimum: 0
        nodes:
          type: array
          items:
            type: string
        status:
          type: string
          enum:
          - stable
          - unstable
          - unreachable
      required:
      - memoryTotal
      - memoryUsed
      - diskTotal
      - diskUsed
      - nodes
      - status
    QdbError:
      properties:
        message:
          type: string
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
    UrlParam:
      type: apiKey
      name: token
      in: query
