openapi: 3.2.0
info:
  title: QuasarDB Tags API
  version: 3.15.0-nightly.0
  description: Find out more at https://doc.quasardb.net
servers:
- url: /api
security:
- Bearer: []
- UrlParam: []
tags:
- name: Tags
paths:
  /tags:
    get:
      operationId: get-tags
      parameters:
      - in: query
        name: regex
        required: false
        schema:
          type: string
      responses:
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QdbError'
        '500':
          description: Internal Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QdbError'
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResult'
              example:
                tables:
                - name: tags
                  columns:
                  - name: tag
                    type: string
                    data:
                    - tag1
                    - tag2
      tags:
      - Tags
      summary: Query the database for all tag names
components:
  schemas:
    QueryResult:
      type: object
      properties:
        tables:
          type: array
          items:
            $ref: '#/components/schemas/QueryTable'
      required:
      - tables
    QdbError:
      properties:
        message:
          type: string
    QueryColumn:
      properties:
        name:
          type: string
        type:
          type: string
        data:
          type: array
          items:
            type: object
    QueryTable:
      properties:
        name:
          type: string
        columns:
          type: array
          items:
            $ref: '#/components/schemas/QueryColumn'
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
    UrlParam:
      type: apiKey
      name: token
      in: query
