openapi: 3.2.0
info:
  title: QuasarDB Parallelism API
  version: 3.15.0-nightly.0
  description: Find out more at https://doc.quasardb.net
servers:
- url: /api
security:
- Bearer: []
- UrlParam: []
tags:
- name: parallelism
paths:
  /option/parallelism:
    get:
      operationId: get-parallelism
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: integer
                format: int64
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QdbError'
      tags:
      - parallelism
      summary: Get the client max parallelism for this logged-in user
components:
  schemas:
    QdbError:
      properties:
        message:
          type: string
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
    UrlParam:
      type: apiKey
      name: token
      in: query
